### ISSUE TITLE
Formular Solver

### ISSUE THREAD

**Issue by olliklee** [GCWizard/GCWizard#1700]
Complete crashes the app, when a variable accidently calls itself a few times: 

```{"id":6,"name":"test","formulas":[{"id":1,"formula":"[A][B]"}],"values":[{"id":1,"key":"A","value":"len(aaaaaaaaaa)"},{"id":2,"key":"B","value":"cos(2.7)"}]}```

This runs in an exponential raising output string, but only if more variables are added. If the B variable is deleted, the functions acts  normal.

**Comment by S-Man42** [comment]
No. It is exaclty working as defined. We just have to think about adjusting the logic to avoid this.

Only interesting thing is: Are you quite sure about the freeze? Well, even my emulator is well working. It's just a very long and hence maybelong building output.

![grafik](https://github.com/user-attachments/assets/bba085e2-29df-4787-9c3a-8da3e6a5b7b5)

**Comment by S-Man42** [comment]
I don't really know how to solve it. One could check whether the variable contains itself. But where to end? It could be that A contains B and B contains C and C contains D and D contains A and even much more complicated. One has to think about a cyclic checker... Well, I personally believe: "Shit in shit out" is a good option here, as long it is no crash. And the nested depth is threshold by (number of variables)^2. So it could be a big number, but no endless loop.

**Comment by S-Man42** [comment]
close due to #1988
