### ISSUE TITLE
Polygraphie et universelle by J. Trithemius

### ISSUE THREAD

**Issue by S-Man42** [GCWizard/GCWizard#1813]
https://archive.org/details/polygraphieetvni00trit/page/182
https://archive.org/details/polygraphieetvni00trit/page/n407
https://archive.org/details/polygraphieetvni00trit/page/183
https://archive.org/details/polygraphieetvni00trit/page/n411 (Achtung: Das untere haben wir schon als "Alchemie Alphabet", sollten wir vielleicht zumindest anders referenzieren?)
https://archive.org/details/polygraphieetvni00trit/page/186
https://archive.org/details/polygraphieetvni00trit/page/n415
https://archive.org/details/polygraphieetvni00trit/page/n603
https://archive.org/details/polygraphieetvni00trit/page/281
https://archive.org/details/polygraphieetvni00trit/page/n605
https://archive.org/details/polygraphieetvni00trit/page/288
https://archive.org/details/polygraphieetvni00trit/page/289
https://archive.org/details/polygraphieetvni00trit/page/n627

**Comment by olliklee** [comment]
How do we call those tables? And do we license them? Are they free to use?

**Comment by S-Man42** [comment]
bpl.org/digitization/locations
describes that the scans can be used freely. (I would use this as the license link)
