### ISSUE TITLE
Ohlsen Telegraph: Error in execution or in the interface

### ISSUE THREAD

**Issue by Linsty** [GCWizard/GCWizard#1843]
Hi

The function Ohlesen Telegraph is not working correctly or the user interface is faulty.

### Encrypt
When typing text or numbers into the text field, no result is shown in the Display Output and Codepoints sections.
![afbeelding](https://github.com/user-attachments/assets/cb86657b-4912-4d0d-ac5b-0276fc280ede)

### Decrypt - Text mode
When typing Codepoints into the text field, no results are shown in the 'Text' section. However, 'Display Output' does show the graphical output.
![afbeelding](https://github.com/user-attachments/assets/c1f4b13e-0275-4830-9807-f73b58127f25)

### Decrypt - Visual mode
When creating a visual sign: There is no result in the Text section. Codepoints shows the correct result, and Display Output shows the graphical output.

If the function works properly:
- The Encrypt/Decrypt option should be removed (or Text mode should be included in the Encrypt section, and only Visual mode should be available in the Decrypt section).
- The Text section should be removed from the results in both Text mode and Visual mode.
![afbeelding](https://github.com/user-attachments/assets/f4075a10-f6ad-4605-b01f-816931bbbc66)

f the function doesn't work properly:
Please add a Beta sign to the function so it's clear that it is not working optimally right now.

Kind regards,

Marcia

**Comment by t-m-z** [comment]
The position of the flaps was added together to form a number that represented a specific entry in the code book. Hence there is no specific alphabet - only a codebook.
This means, encoding ist not really usefull. I will have a look at it how to adapt the tool.

**Comment by t-m-z** [comment]
The manual is updatetd,

**Comment by t-m-z** [comment]
**Encrypt**:
GC Wizard only allows text from the codebook which will be encrypted to flaps and codepoints
Example: seilere sees, som kommer nord fra. => 001

**Decrypt - Text mode**
Codepoints will be decrypted with the relevant text from the codebook. Of there is no entry, there will be no ouput. I will change this.

**Decrypt - Visual mode**
Flaps will be decrypted with the relevant text from the codebook. Of there is no entry, there will be no ouput. I will change this.
