### ISSUE TITLE
DCFI Grid

### ISSUE THREAD

**Issue by S-Man42** [GCWizard/GCWizard#1867]
Good morning,

I am looking for a very precise coding system and unless I am mistaken, I have not found it on your site.
These are GPS coordinates converted by “DFCI Grid”.
This is a code used by firefighters.

For example, for this puzzle: GC7967B

The owner says the cross to look for is here: HG00E7.3
We need to convert HG00E7.3 into "normal" coordinates.
But how?

I searched the internet for an online converter but couldn't find one.
On the other hand, it seems to be possible with a Garmin type GPS (I don't have one) and perhaps with an application only available on Android (I'm on IOS).

If you don't know this coding system, you have some information here:
http://ccffpeynier.free.fr/Files/dfci.pdf
http://www.geonov.fr/smartdata/carroyage/
http://feuxdeforet.fr/cartes/dfci/

If you are lucky enough to discover an online solver, I am very interested. But maybe it is already on your site?
Thank you in advance for your response.

Lola

**Comment by t-m-z** [comment]
regarding 
- https://viglino.github.io/ol-ext/examples/layer/map.dfci.html DFCI 
- https://www.valabre.com/actualites/retour-sur-le-carroyage-dfci
DFCI is used only in France.
Hence I am not convinced to  implement it.
