### ISSUE TITLE
Symbol Replacer Bug

### ISSUE THREAD

**Issue by SzpiegDonPedro** [GCWizard/GCWizard#1999]
When I tested Symbol Replacer, after pressing the “Find matching symbol table” button, the iOS app turned itself off and took me to the home screen.

**Comment by olliklee** [comment]
Could you give me more information? Maybe a screen shot?

**Comment by SzpiegDonPedro** [comment]
Yes, it turn off when i click:
1. Symbol replacer
2. Magic tool
3. Find matching symbol table(slow)![image](https://github.com/user-attachments/assets/59ec0816-07c8-4aa9-86e9-03e7df729cac)
And after this app turn off.
