### ISSUE TITLE
Amino Acids Overview Bug

### ISSUE THREAD

**Issue by SzpiegDonPedro** [GCWizard/GCWizard#2001]
This tool won't load - a gray screen appears.

**Comment by t-m-z** [comment]
reproduced on 
- Web
- Android Gold Build 295

**Comment by t-m-z** [comment]
Unsupported operation: sort
line 36
packages/gc_wizard/tools/science_and_technology/dna/dna_aminoacids_table/widget/dna_aminoacids_table.dart

**Comment by SzpiegDonPedro** [comment]
Can i help you with that problem???

**Comment by t-m-z** [comment]
I am not quite sure.
For me this seems to be a flutter/dart bug.

Sent from MailDroid

-----Original Message-----

**Comment by Mike-3** [comment]
@SzpiegDonPedro: Please do not close the issue, when we have a open brach to this issue.
The problem is, if we don't merge the branch, we have an open issue marked as closed.
Is automaticly closed, when we merge the branch.

**Comment by SzpiegDonPedro** [comment]
@Mike-3 Sorry for that. I will remember it for the future - I will close it when the new version comes to upstream
