### ISSUE TITLE
Password Generator upgrade

### ISSUE THREAD

**Issue by SzpiegDonPedro** [GCWizard/GCWizard#2013]
while browsing the password generator I noticed the possibility of adding an interesting function that is easy to program - the strength of the password and the time needed to crack it

**Comment by S-Man42** [comment]
Do you have an algorithm for calculating the strength? Is it somewhere standardized?

The time to crack depends on so many factors that it is absolutely impossible to calculate a general result. The first one is: How fast is your device? And this is different from device to device. So you cannot return a value which is equal for everybody. Hence it is pretty useless in terms of Mystery Solving (Geocaching).

**Comment by SzpiegDonPedro** [comment]
E.g: https://github.com/Bek0/password-strength-checker

in fact this function is not useful for puzzles on GC but not every tool is for puzzles:) This function could only serve as a reference

**Comment by S-Man42** [comment]
https://en.m.wikipedia.org/wiki/Password_strength

Two measurements:
-> Bit entropy
-> Shannon
