### ISSUE TITLE
Reverse wherigo solver

### ISSUE THREAD

**Issue by SzpiegDonPedro** [GCWizard/GCWizard#2014]
Hi all, today while browsing through GCW functions I noticed that there is no separate wherigo solver for reverse wherigo. 
This function is on many cache sites on the internet but it is missing in GCW, so I propose to add it to the collection.
This function is on many cache sites on the internet but it is missing in GCW, so I propose to add it to the collection.
Additional links for some solvers in Web:

https://gc.de/gc/reversewherigo/

https://www.cachesleuth.com/reversewherigo.html

https://github.com/avogadogc/revwherigo

**Comment by AndyPuma** [comment]
this function is in coordinates Format Converter for 3 Typs of Reverse WIGs
;-) search for Waldmeister

SzpiegDonPedro ***@***.***> schrieb am Mi., 20. Nov. 2024,
15:28:

**Comment by S-Man42** [comment]
We have 3 different solvers in the coordinates section (they are handled as coordinate formats)

**Comment by S-Man42** [comment]
You can find the right tool when you search for reversewig or similar.

**Comment by SzpiegDonPedro** [comment]
Oooooh... sorry. I missed it because it wasn't in tools
