### ISSUE TITLE
Symbol Replacer bug

### ISSUE THREAD

**Issue by SzpiegDonPedro** [GCWizard/GCWizard#2027]
While browsing the function symbol replacer, the application hung in a dead spot: I managed to make a screenshot.![image](https://github.com/user-attachments/assets/e56c31fc-b268-421f-9fd0-3f73473ad59f)

Probably there, as before, you have to limit something in the code

**Comment by Mike-3** [comment]
I found the problem, the path to pl and es language was wrong.
