### ISSUE TITLE
Substitution Breaker Bug

### ISSUE THREAD

**Issue by SzpiegDonPedro** [GCWizard/GCWizard#2029]
When reviewing the functions of the application after entering the Polish word, the application crashed. Screenshot under:![image](https://github.com/user-attachments/assets/59f3e80c-4f06-44be-a785-ec880a24ebde)

**Comment by Mike-3** [comment]
This is the same problem as with the Replacer. The Replacer uses the Substitution Breaker. So this should be fixed with the bugfix.

**Comment by SzpiegDonPedro** [comment]
Ok, so i wait for this pull request. Thanks for your answer
